In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
N = 10
np.random.seed(48)
X = np.random.randint(0, 100, size=(N, N))
X

array([[ 0, 51, 81, 68, 91, 48, 64, 70, 70, 34],
       [92, 80, 29,  6, 86, 31, 46, 48, 91, 28],
       [58, 15, 30, 66, 18, 53, 18, 21, 25, 92],
       [34, 27, 60, 34, 45, 42, 92, 49, 21,  6],
       [47, 16, 37, 13, 22, 54, 92, 12, 85, 26],
       [22,  2, 61, 21,  7, 35, 50, 64, 67,  3],
       [92, 15, 32,  2, 49, 43, 14, 57, 83, 89],
       [92,  1, 23, 52,  2, 65, 74, 54,  3, 76],
       [21, 59, 96, 55, 68, 79, 60, 46, 49, 57],
       [35, 14, 80, 99, 96, 68, 32, 17, 28, 16]])

Kernel:
\begin{equation}
    \mathbf{K} = \mathbf{X}^{} \mathbf{X}^{T}
\end{equation}
Covariance matrix:
\begin{equation}
     \mathbf{X}^{T} \mathbf{X}^{}
\end{equation}

Even though X is not necessarily symmetric and positively defined, the kernel and the covariance matrix are.

In [22]:
# Definition of Kernel
K = X @ np.transpose(X)
K

array([[39423, 29777, 19365, 25652, 22853, 21260, 23738, 20062, 36933,
        31668],
       [29777, 37583, 17680, 21067, 23592, 17319, 29576, 20107, 29086,
        22902],
       [19365, 17680, 21832, 13219, 14617, 10698, 21526, 22487, 22539,
        19611],
       [25652, 21067, 13219, 21772, 18943, 16122, 15890, 19096, 25460,
        21371],
       [22853, 23592, 14617, 18943, 23912, 16781, 20515, 19108, 23679,
        17844],
       [21260, 17319, 10698, 16122, 16781, 17018, 16072, 14395, 20230,
        15421],
       [23738, 29576, 21526, 15890, 20515, 16072, 32222, 23339, 25330,
        18981],
       [20062, 20107, 22487, 19096, 19108, 14395, 23339, 30104, 23733,
        19420],
       [36933, 29086, 22539, 25460, 23679, 20230, 25330, 23733, 38394,
        31572],
       [31668, 22902, 19611, 21371, 17844, 15421, 18981, 19420, 31572,
        33815]])

In [23]:
# Definition of Covariance matrix
Cov = np.transpose(X) @  X
Cov

array([[34271, 13145, 19405, 16197, 21154, 24637, 24304, 21045, 25926,
        26341],
       [13145, 14118, 16522, 10819, 19465, 14114, 15542, 13229, 17817,
        10936],
       [19405, 16522, 34161, 25924, 30168, 28925, 29502, 23822, 27220,
        19179],
       [16197, 10819, 25924, 26316, 23301, 24356, 21534, 16735, 15971,
        18006],
       [21154, 19465, 30168, 23301, 34804, 25448, 24604, 21454, 28023,
        17946],
       [24637, 14114, 28925, 24356, 25448, 28918, 28362, 21658, 24862,
        23495],
       [24304, 15542, 29502, 21534, 24604, 28362, 36260, 23976, 27438,
        19016],
       [21045, 13229, 23822, 16735, 21454, 21658, 23976, 22856, 23753,
        18525],
       [25926, 17817, 27220, 15971, 28023, 24862, 27438, 23753, 36044,
        20621],
       [26341, 10936, 19179, 18006, 17946, 23495, 19016, 18525, 20621,
        28327]])

$\mathbf{np.linalg.eigh}$ : return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix, like in the case being.

In [28]:
eigval_K, eigvect_K = np.linalg.eigh(K)

In [29]:
eigval_Cov, eigvect_Cov = np.linalg.eigh(Cov)

In [30]:
eigval_K - eigval_Cov

array([-1.15107923e-12,  2.30784281e-11,  6.82121026e-13, -1.54614099e-11,
       -1.81898940e-12,  2.36468622e-11, -5.45696821e-12, -3.63797881e-12,
        3.63797881e-12, -2.91038305e-11])

Eigenvalues of the kernel and covariance matrix are identical up to sensitivity of the calculation.